{{- if .Values.kafkaConnect.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cass-cdc-pg.fullname" . }}-kafka-connect
  labels:
    {{- include "cass-cdc-pg.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cass-cdc-pg.fullname" . }}-kafka-connect
  minReplicas: {{ .Values.kafkaConnect.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.kafkaConnect.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.kafkaConnect.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.kafkaConnect.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.kafkaConnect.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.kafkaConnect.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
