{{- if and .Values.monitoring.prometheus.enabled .Values.monitoring.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cass-cdc-pg.fullname" . }}-kafka-connect
  {{- if .Values.monitoring.prometheus.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.prometheus.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "cass-cdc-pg.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cass-cdc-pg.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kafka-connect
  endpoints:
    - port: http
      path: {{ .Values.monitoring.prometheus.path }}
      interval: {{ .Values.monitoring.prometheus.interval }}
      scheme: http
{{- end }}
